### ISSUE TITLE
queryCoordinateForPixel returns inaccurate data

### ISSUE THREAD

**Issue by ghosalmartin** [rinigus/mapbox-gl-qml#29]
https://github.com/ghosalmartin/harbour-uber/blob/master/qml/MapPage.qml

Issue occurs above, not quite sure why but hey ho I could be doing something wrong

**Comment by rinigus** [comment]
I couldn't reproduce it on PC, the clicks were converted quite closely to what I was clicking to (very small error, but nothing like you showed).

Looking at your code, taking mouse coordinates is probably not what you want to do in this case.  Namely, you are pressing on icon and are processing the coordinates where your finger was, not the pin. So, you could just use the reference location of your pin as coordinates to process (map.width/2 , map.height/2 should work)

I think that you were trying to suggest it yourself while we chatted, I just didn't realized that.

Try if this helps and let me know :)

**Comment by ghosalmartin** [comment]
Thats fixed the issue thanks :D

**Comment by rinigus** [comment]
excellent, thank you!
