### ISSUE TITLE
 #include <QMapboxGL> not found

### ISSUE THREAD

**Issue by ducmaxime** [rinigus/mapbox-gl-qml#30]
Hello,

I try to test your application but I have #include <QMapboxGL> not found error.

Any idea ?

**Comment by rinigus** [comment]
You have to install qmapboxgl library. For Sailfish OS, its packaged via https://github.com/rinigus/pkg-mapbox-gl-native . For other OS options, consult https://github.com/mapbox/mapbox-gl-native and install Qt version.

**Comment by rinigus** [comment]
I am closing the issue since its an issue with mapboxgl install, not qml plugin as such.
