### ISSUE TITLE
running the project problem! (windows 10, 64 bit)

### ISSUE THREAD

**Issue by unkowndfrt** [rinigus/mapbox-gl-qml#37]
Hi,

When I build and run the project under QT5.9 on windows 10, I got this error:
:-1: error: libcurl development package not found

Please help me.

**Comment by rinigus** [comment]
Which project are you trying to run? In 5.9, there is maybe no need to use libcurl workaround for Qt bug. So, you could use plain qmapboxgl and this widget without libcurl.

So, project files:

* https://github.com/rinigus/mapbox-gl-qml/blob/master/mapbox-gl-qml.pro This is currently used in Sailfish OS to build the widget as installable library. You don't need to specify QMAKE_ options (comment them out) and comment out libcurl line

* https://github.com/rinigus/mapbox-gl-qml/blob/master/app/mapbox-qml.pro example app project. this is where you probably want to start. You will have to adjust `LIBS` variable and remove `-L...` and `-lcurl`

**Comment by tmpsantos** [comment]
@unkowndfrt we publish QMapboxGL binaries compatible with Qt5 and MSVC here on our build bots https://ci.appveyor.com/project/Mapbox/mapbox-gl-native/build/3251/artifacts

**Comment by rinigus** [comment]
closing
