### ISSUE TITLE
Compilation error in mapbox-gl-qml on Arch Linux (setFramebufferObject not available)

### ISSUE THREAD

**Issue by fgossel** [rinigus/mapbox-gl-qml#54]
While trying to install the pure-maps application on Arch Linux, I encountered a compilation issue with the mapbox-gl-qml dependency. Specifically, during the compilation of qsgmapboxglnode.cpp, the error occurs due to the setFramebufferObject method, which does not exist in the QMapLibre::Map class. I believe the correct method to use is setOpenGLFramebufferObject.
Reference:
https://maplibre.org/maplibre-native-qt/docs/functions_func.html 

After manually modifying this line in qsgmapboxglnode.cpp, the compilation was successful, and the package built correctly.

It seems that in the latest version of the QMapLibre library, the API was updated, and the setFramebufferObject method was either removed or renamed to setOpenGLFramebufferObject. This change allows for successful compilation and functionality of the package.

```
--- qsgmapboxglnode.cpp.orig	2024-09-28 14:35:31.440696394 +0200
+++ qsgmapboxglnode.cpp	2024-09-28 14:43:45.631138107 +0200
@@ -152 +152 @@ void QSGMapboxGLTextureNode::resize(cons
-  m_map->setFramebufferObject(m_fbo->handle(), fbSize); //minSize);
+  m_map->setOpenGLFramebufferObject(m_fbo->handle(), fbSize);
```

**Comment by fgossel** [comment]
Considering the PR Bump to version 3.0.0 (#53), I believe that my patch is likely unnecessary for the upstream repository. It might be more appropriate for me to submit this patch to the AUR for integration until the update is released.

**Comment by rinigus** [comment]
Good find! I haven't tested it with recent MapLibre versions. Please submit as PR into the master branch here.

**Comment by rinigus** [comment]
but which version of maplibre did you use?

**Comment by fgossel** [comment]
In Arch Linux, MapLibre is in the Git version. I have been noticing the error for a while in the recent updates. Currently, it is version maplibre-native-git 2.1.0.r95.gb2b74d6-1.

**Comment by fgossel** [comment]
@rinigus PR submitted.

**Comment by rinigus** [comment]
Thanks!

**Comment by rinigus** [comment]
Fixed in https://github.com/rinigus/mapbox-gl-qml/pull/55
